// Generated by CoffeeScript 1.6.2
(function() {
  var Markers;

  Markers = new Mongo.Collection('markers');

  if (Meteor.isClient) {
    Template.map.onCreated(function() {
      GoogleMaps.ready('map', function(map) {
        var markers;

        google.maps.event.addListener(map.instance, 'click', function(event) {
          Markers.insert({
            lat: event.latLng.lat(),
            lng: event.latLng.lng()
          });
        });
        markers = {};
        Markers.find().observe({
          added: function(document) {
            var icons, marker;

            marker = new google.maps.Marker({
              draggable: true,
              animation: google.maps.Animation.DROP,
              position: new google.maps.LatLng(document.lat, document.lng)
            }, icons = {
              Fire: {
                icon: "/icon/fire-icon.png"
              }
            }, {
              map: map.instance,
              id: document._id
            });
            google.maps.event.addListener(marker, 'dragend', function(event) {
              Markers.update(marker.id, {
                $set: {
                  lat: event.latLng.lat(),
                  lng: event.latLng.lng()
                }
              });
            });
            markers[document._id] = marker;
          },
          changed: function(newDocument, oldDocument) {
            markers[newDocument._id].setPosition({
              lat: newDocument.lat,
              lng: newDocument.lng
            });
          },
          removed: function(oldDocument) {
            markers[oldDocument._id].setMap(null);
            google.maps.event.clearInstanceListeners(markers[oldDocument._id]);
            delete markers[oldDocument._id];
          }
        });
      });
    });
    Meteor.startup(function() {
      GoogleMaps.load();
    });
    Template.map.helpers({
      mapOptions: function() {
        if (GoogleMaps.loaded()) {
          navigator.geolocation.getCurrentPosition;
          return {
            center: new google.maps.LatLng(navigator.geolocation.getCurrentPosition.lat, navigator.geolocation.getCurrentPosition.lng),
            zoom: 8
          };
        }
      }
    });
  }

}).call(this);

/*
//@ sourceMappingURL=SAT.map
*/
