// Generated by CoffeeScript 1.6.2
(function() {
  var FiresDB;

  FiresDB = new Mongo.Collection('Fires');

  if (Meteor.isClient) {
    Template.map.onCreated(function() {
      GoogleMaps.ready('map', function(map) {
        google.maps.event.addListener(map.instance, 'click', function(event) {
          if (Meteor.isCordova) {

          } else {

          }
          FiresDB.insert({
            lat: event.latLng.lat(),
            lng: event.latLng.lng()
          });
          new google.maps.InfoWindow({
            content: "BLA"
          }).open(map, marker);
        });
        FiresDB.find().observe({
          added: function(document) {
            var marker;

            marker = new google.maps.Marker({
              draggable: !Meteor.isCordova,
              animation: google.maps.Animation.DROP,
              position: new google.maps.LatLng(document.lat, document.lng),
              map: map.instance,
              id: document._id
            });
            google.maps.event.addListener(marker, 'dragend', function(event) {
              FiresDB.update(marker.id, {
                $set: {
                  lat: event.latLng.lat(),
                  lng: event.latLng.lng()
                }
              });
            });
            FiresDB[document._id] = marker;
          },
          changed: function(newDocument, oldDocument) {
            FiresDB[newDocument._id].setPosition({
              lat: newDocument.lat,
              lng: newDocument.lng
            });
          },
          removed: function(oldDocument) {
            FiresDB[oldDocument._id].setMap(null);
            google.maps.event.clearInstanceListeners(FiresDB[oldDocument._id]);
            delete FiresDB[oldDocument._id];
          }
        });
      });
    });
    Meteor.startup(function() {
      GoogleMaps.load();
    });
    Template.map.helpers({
      mapOptions: function() {
        var MyLocation;

        if (GoogleMaps.loaded()) {
          MyLocation = {
            lat: "-33.833",
            lng: "117.159"
          };
          if (navigator.geolocation.getCurrentPosition === !null) {
            MyLocation = Geolocation.latLng;
          }
          return {
            center: new google.maps.LatLng(MyLocation.lat, MyLocation.lng),
            zoom: 14
          };
        }
      }
    });
    return;
  }

}).call(this);

/*
//@ sourceMappingURL=SAT.map
*/
