// Generated by CoffeeScript 1.6.2
(function() {
  App.info({
    id: 'com.HackIt.GovHack-Perth.SAT',
    name: 'SAT',
    description: 'Situational Awareness Tool For country volunteer firefighters',
    author: 'Matt Development Group',
    email: 'contact@example.com',
    website: 'http://example.com'
  });

  App.setPreference('BackgroundColor', '0xff0000ff');

  App.setPreference('HideKeyboardFormAccessoryBar', true);

  App.accessRule('*.google.com/*');

  App.accessRule('*.googleapis.com/*');

  App.accessRule('*.gstatic.com/*');

}).call(this);

/*
//@ sourceMappingURL=mobile-config.map
*/
